In [ ]:
!pip install -q kaggle

In [ ]:
import os
print(os.listdir())

['.config', 'kaggle.json', 'sample_data']

In [ ]:
import os
import shutil

os.makedirs("/root/.kaggle", exist_ok=True)

shutil.move("kaggle.json", "/root/.kaggle/kaggle.json")

os.chmod("/root/.kaggle/kaggle.json", 600)

In [ ]:
!kaggle datasets list -s fashion

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
ref                                                       title                                     size  lastUpdated                 downloadCount  voteCount  usabilityRating
--------------------------------------------------------  ---------------------------------  -----------  --------------------------  -------------  ---------  ---------------
zalando-research/fashionmnist                             Fashion MNIST                         72114846  2017-12-07 00:54:20.537000         292707       3209  0.85294116
bhanupratapbiswas/fashion-products                        Fashion Products                         20181  2023-06-12 03:56:26.747000          11132        130  1
paramaggarwal/fashion-product-images-dataset              Fashion Product Images Dataset     24771215740  2019-03-14 18:57:43.307000          90558        861  1
paramaggarwal/fashion-product-images-small                Fashion Product Images (Small)       592614936  2019-04-26 16:33:51.490000          71438        469  1
validmodel/indo-fashion-dataset                           Indo fashion dataset                2892352727  2025-04-07 15:21:04.673000           5418         75  1
shivamb/fashion-clothing-products-catalog                 Fashion Clothing Products Dataset       629653  2021-12-03 18:18:54.547000          15708        149  1
manishmathias/myntra-fashion-dataset                      Myntra Fashion                        20508035  2022-06-05 07:58:16.587000           7540         55  0.7647059
nitinsss/fashion-dataset-with-over-15000-labelled-images  Fashion Dataset                         448516  2019-12-17 01:11:36.583000           4025         45  1
jocelyndumlao/global-fashion-brands                       Global Fashion Brands                    20368  2023-09-03 00:52:54.443000           4695        113  0.875
atharvasoundankar/fashion-retail-sales                    🛍️ Fashion Retail Sales Dataset          31656  2025-04-01 05:05:48.020000           9373         89  1
rahul2312kaggle/fashion-dataset                           Fashion Dataset                           4744  2025-03-21 17:17:33.713000           2572         31  0.9411765
andhikawb/fashion-mnist-png                               Fashion MNIST PNG                     46832169  2024-01-31 11:24:44.130000           2251         33  0.875
ricgomes/global-fashion-retail-stores-dataset             Global Fashion Retail Sales          234910599  2025-03-19 18:37:15.857000           8719         60  1
tiyabk/sustainable-fashion                                sustainable-fashion                    8202302  2025-01-08 20:25:58.183000           1318         30  1
bhavikjikadara/e-commerce-products-images                 Fashion Products Images              296667796  2024-02-21 05:04:04.707000           1537         36  1
hiteshsuthar101/myntra-fashion-product-dataset            Myntra Fashion Product Dataset      3118542478  2022-11-08 12:52:59.640000           6234         48  0.9411765
durgeshrao9993/dataset                                    Women Fashion Trend Dataset             359238  2023-06-22 21:43:35.943000           2350         65  1
sanjeet41/fashionmnist-train                              Fashion-mnist_train                   35194054  2018-07-11 05:19:32.247000           4100         29  0.7647059
latifahhukma/fashion-campus                               Fashion Campus                      1147614101  2022-11-12 07:39:03.797000           1903         35  0.47058824
fekihmea/fashion-retail-sales                             Fashion Retail Sales                     32519  2023-10-31 11:55:52.227000           6837         46  0.7058824

In [ ]:
!kaggle datasets download -d paramaggarwal/fashion-product-images-dataset

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/paramaggarwal/fashion-product-images-dataset
License(s): MIT
Downloading fashion-product-images-dataset.zip to /content
100% 23.1G/23.1G [04:08<00:00, 99.8MB/s]

In [ ]:
!unzip -q fashion-product-images-dataset.zip

In [ ]:
import os

os.listdir()
os.listdir("fashion-dataset")

['styles.csv', 'fashion-dataset', 'styles', 'images.csv', 'images']

In [ ]:
os.listdir("fashion-dataset/images")[:10]

['26863.jpg',
 '45371.jpg',
 '10097.jpg',
 '11119.jpg',
 '41270.jpg',
 '42407.jpg',
 '9752.jpg',
 '18497.jpg',
 '27509.jpg',
 '49709.jpg']

In [ ]:
import pandas as pd

styles = pd.read_csv("fashion-dataset/styles.csv", on_bad_lines="skip")
styles.head()
styles.info()
styles.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44424 entries, 0 to 44423
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  44424 non-null  int64
 1   gender              44424 non-null  object
 2   masterCategory      44424 non-null  object
 3   subCategory         44424 non-null  object
 4   articleType         44424 non-null  object
 5   baseColour          44409 non-null  object
 6   season              44403 non-null  object
 7   year                44423 non-null  float64
 8   usage               44107 non-null  object
 9   productDisplayName  44417 non-null  object
dtypes: float64(1), int64(1), object(8)
memory usage: 3.4+ MB

Index(['id', 'gender', 'masterCategory', 'subCategory', 'articleType',
       'baseColour', 'season', 'year', 'usage', 'productDisplayName'],
      dtype='object')

In [ ]:
styles["masterCategory"].value_counts()

masterCategory
Apparel           21397
Accessories       11274
Footwear           9219
Personal Care      2403
Free Items          105
Sporting Goods       25
Home                  1
Name: count, dtype: int64

In [ ]:
styles["subCategory"].value_counts()

subCategory
Topwear                     15402
Shoes                        7343
Bags                         3055
Bottomwear                   2694
Watches                      2542
Innerwear                    1808
Jewellery                    1079
Eyewear                      1073
Fragrance                    1011
Sandal                        963
Wallets                       933
Flip Flops                    913
Belts                         811
Socks                         698
Lips                          527
Dress                         478
Loungewear and Nightwear      470
Saree                         427
Nails                         329
Makeup                        307
Headwear                      293
Ties                          258
Accessories                   129
Scarves                       118
Cufflinks                     108
Apparel Set                   106
Free Gifts                    104
Stoles                         90
Skin Care                      77
Skin                           69
Eyes                           43
Mufflers                       38
Shoe Accessories               24
Sports Equipment               21
Gloves                         20
Hair                           19
Bath and Body                  12
Water Bottle                    7
Perfumes                        6
Umbrellas                       6
Beauty Accessories              4
Wristbands                      4
Sports Accessories              3
Home Furnishing                 1
Vouchers                        1
Name: count, dtype: int64

In [ ]:
styles["articleType"].value_counts().head(30)

articleType
Tshirts                  7067
Shirts                   3217
Casual Shoes             2845
Watches                  2542
Sports Shoes             2036
Kurtas                   1844
Tops                     1762
Handbags                 1759
Heels                    1323
Sunglasses               1073
Wallets                   936
Flip Flops                914
Sandals                   897
Briefs                    849
Belts                     813
Backpacks                 724
Socks                     686
Formal Shoes              637
Perfume and Body Mist     613
Jeans                     609
Shorts                    547
Trousers                  530
Flats                     500
Bra                       477
Dresses                   464
Sarees                    427
Earrings                  416
Deodorant                 347
Nail Polish               329
Lipstick                  315
Name: count, dtype: int64

In [ ]:
styles["gender"].value_counts()

gender
Men       22147
Women     18631
Unisex     2161
Boys        830
Girls       655
Name: count, dtype: int64

In [ ]:
styles["season"].value_counts()

season
Summer    21472
Fall      11431
Winter     8517
Spring     2983
Name: count, dtype: int64

In [ ]:
styles["usage"].value_counts()

usage
Casual          34406
Sports           4025
Ethnic           3208
Formal           2345
Smart Casual       67
Party              29
Travel             26
Home                1
Name: count, dtype: int64

In [ ]:
styles = styles[
    styles["masterCategory"].isin([
        "Apparel",
        "Footwear"
    ])
]

In [ ]:
print(len(styles))

30616

In [ ]:
styles = styles.dropna()

In [ ]:
styles = styles.drop_duplicates(subset="id")

In [ ]:
styles["articleType"].value_counts().head(25)

articleType
Tshirts            7065
Shirts             3214
Casual Shoes       2845
Sports Shoes       2016
Kurtas             1844
Tops               1762
Heels              1323
Flip Flops          914
Sandals             895
Briefs              847
Formal Shoes        637
Jeans               603
Shorts              547
Trousers            530
Flats               500
Bra                 477
Dresses             464
Sarees              427
Track Pants         304
Sweatshirts         285
Sweaters            277
Jackets             258
Innerwear Vests     242
Kurtis              234
Tunics              229
Name: count, dtype: int64

In [ ]:
#Curated List of categories
selected_articles = [
    # Tops
    "Tshirts",
    "Shirts",
    "Tops",
    "Kurtas",
    "Kurtis",
    "Tunics",
    "Sweatshirts",
    "Sweaters",
    "Jackets",

    # Bottoms
    "Jeans",
    "Trousers",
    "Shorts",
    "Track Pants",

    # Dresses
    "Dresses",
    "Sarees",

    # Footwear
    "Casual Shoes",
    "Sports Shoes",
    "Formal Shoes",
    "Heels",
    "Flats",
    "Sandals",
    "Flip Flops"
]

styles = styles[styles["articleType"].isin(selected_articles)]

print("Remaining products:", len(styles))
print()
print(styles["articleType"].value_counts())

Remaining products: 27173

articleType
Tshirts         7065
Shirts          3214
Casual Shoes    2845
Sports Shoes    2016
Kurtas          1844
Tops            1762
Heels           1323
Flip Flops       914
Sandals          895
Formal Shoes     637
Jeans            603
Shorts           547
Trousers         530
Flats            500
Dresses          464
Sarees           427
Track Pants      304
Sweatshirts      285
Sweaters         277
Jackets          258
Kurtis           234
Tunics           229
Name: count, dtype: int64

Introducing Capping on items

In [ ]:
caps = {
    "Tshirts": 500,
    "Shirts": 500,
    "Casual Shoes": 500,
    "Sports Shoes": 500,
    "Kurtas": 500,
    "Tops": 500,
    "Heels": 400,
    "Flip Flops": 300,
    "Sandals": 300,
    "Formal Shoes": 300,
    "Jeans": 500,
    "Shorts": 400,
    "Trousers": 400,
    "Flats": 300
}

balanced = []

for article, group in styles.groupby("articleType"):
    if article in caps:
        balanced.append(
            group.sample(
                n=min(len(group), caps[article]),
                random_state=42
            )
        )
    else:
        balanced.append(group)

styles_balanced = pd.concat(balanced)

print(len(styles_balanced))

8378

In [ ]:
styles_balanced["articleType"].value_counts()

articleType
Casual Shoes    500
Tops            500
Sports Shoes    500
Shirts          500
Kurtas          500
Jeans           500
Tshirts         500
Dresses         464
Sarees          427
Heels           400
Trousers        400
Shorts          400
Track Pants     304
Flats           300
Formal Shoes    300
Flip Flops      300
Sandals         300
Sweatshirts     285
Sweaters        277
Jackets         258
Kurtis          234
Tunics          229
Name: count, dtype: int64

In [ ]:
import os

image_folder = "fashion-dataset/images"

styles_balanced["image_exists"] = styles_balanced["id"].apply(
    lambda x: os.path.exists(f"{image_folder}/{x}.jpg")
)

print(styles_balanced["image_exists"].value_counts())

image_exists
True     8377
False       1
Name: count, dtype: int64

In [ ]:
styles_balanced = styles_balanced[
    styles_balanced["image_exists"]
].drop(columns="image_exists")

In [ ]:
import os

os.makedirs("miranda_dataset", exist_ok=True)

styles_balanced.to_csv(
    "miranda_dataset/styles.csv",
    index=False
)

In [ ]:
import shutil
from tqdm import tqdm

source = "fashion-dataset/images"
destination = "miranda_dataset/images"

os.makedirs(destination, exist_ok=True)

for image_id in tqdm(styles_balanced["id"]):
    shutil.copy(
        f"{source}/{image_id}.jpg",
        f"{destination}/{image_id}.jpg"
    )

100%|██████████| 8377/8377 [00:45<00:00, 185.78it/s]

In [ ]:
print("Metadata:", len(styles_balanced))
print("Images:", len(os.listdir("miranda_dataset/images")))

Metadata: 8377
Images: 8377

In [ ]:
styles_balanced = styles_balanced.drop(columns=["year"])

In [ ]:
styles_balanced.to_csv(
    "miranda_dataset/styles.csv",
    index=False
)

In [ ]:

styles_balanced["gender"].value_counts()

gender
Men       4047
Women     3839
Girls      206
Boys       146
Unisex     139
Name: count, dtype: int64

In [ ]:
styles_balanced["baseColour"].value_counts()

baseColour
Black                1830
Blue                 1209
White                 871
Grey                  622
Brown                 583
Navy Blue             454
Green                 391
Red                   385
Pink                  348
Purple                293
Beige                 203
Multi                 137
Yellow                130
Maroon                102
Olive                  96
Cream                  89
Orange                 87
Silver                 71
Gold                   60
Charcoal               57
Off White              42
Magenta                39
Khaki                  36
Peach                  31
Tan                    29
Mustard                28
Lavender               27
Teal                   22
Grey Melange           19
Rust                   18
Turquoise Blue         18
Bronze                 15
Copper                  6
Sea Green               6
Coffee Brown            5
Mushroom Brown          4
Taupe                   4
Mauve                   3
Burgundy                3
Nude                    1
Metallic                1
Fluorescent Green       1
Lime Green              1
Name: count, dtype: int64

In [ ]:
styles_balanced["season"].value_counts()

season
Summer    4154
Fall      3209
Winter     872
Spring     142
Name: count, dtype: int64

In [ ]:

styles_balanced["usage"].value_counts()

usage
Casual          5496
Ethnic          1213
Sports          1005
Formal           631
Party             20
Smart Casual      11
Travel             1
Name: count, dtype: int64

In [ ]:
!ls miranda_dataset

images	styles.csv

In [ ]:
!zip -r miranda_dataset.zip miranda_dataset

Streaming output truncated to the last 5000 lines.
  adding: miranda_dataset/images/25700.jpg (deflated 11%)
  adding: miranda_dataset/images/26184.jpg (deflated 32%)
  adding: miranda_dataset/images/9384.jpg (deflated 17%)
  adding: miranda_dataset/images/43269.jpg (deflated 11%)
  adding: miranda_dataset/images/27300.jpg (deflated 6%)
  adding: miranda_dataset/images/59610.jpg (deflated 20%)
  adding: miranda_dataset/images/8456.jpg (deflated 7%)
  adding: miranda_dataset/images/26389.jpg (deflated 10%)
  adding: miranda_dataset/images/6312.jpg (deflated 22%)
  adding: miranda_dataset/images/6896.jpg (deflated 38%)
  adding: miranda_dataset/images/10500.jpg (deflated 11%)
  adding: miranda_dataset/images/43672.jpg (deflated 6%)
  adding: miranda_dataset/images/52556.jpg (deflated 7%)
  adding: miranda_dataset/images/45390.jpg (deflated 47%)
  adding: miranda_dataset/images/57964.jpg (deflated 16%)
  adding: miranda_dataset/images/59399.jpg (deflated 6%)
  adding: miranda_dataset/images/42565.jpg (deflated 16%)
  adding: miranda_dataset/images/4958.jpg (deflated 30%)
  adding: miranda_dataset/images/19430.jpg (deflated 19%)
  adding: miranda_dataset/images/58501.jpg (deflated 21%)
  adding: miranda_dataset/images/31326.jpg (deflated 10%)
  adding: miranda_dataset/images/8210.jpg (deflated 14%)
  adding: miranda_dataset/images/19876.jpg (deflated 35%)
  adding: miranda_dataset/images/16222.jpg (deflated 21%)
  adding: miranda_dataset/images/28628.jpg (deflated 10%)
  adding: miranda_dataset/images/58003.jpg (deflated 5%)
  adding: miranda_dataset/images/39464.jpg (deflated 2%)
  adding: miranda_dataset/images/46801.jpg (deflated 6%)
  adding: miranda_dataset/images/25420.jpg (deflated 41%)
  adding: miranda_dataset/images/5920.jpg (deflated 9%)
  adding: miranda_dataset/images/6166.jpg (deflated 19%)
  adding: miranda_dataset/images/14060.jpg (deflated 6%)
  adding: miranda_dataset/images/2286.jpg (deflated 8%)
  adding: miranda_dataset/images/13092.jpg (deflated 9%)
  adding: miranda_dataset/images/57499.jpg (deflated 31%)
  adding: miranda_dataset/images/38290.jpg (deflated 9%)
  adding: miranda_dataset/images/44534.jpg (deflated 40%)
  adding: miranda_dataset/images/19955.jpg (deflated 6%)
  adding: miranda_dataset/images/28546.jpg (deflated 11%)
  adding: miranda_dataset/images/15847.jpg (deflated 13%)
  adding: miranda_dataset/images/52922.jpg (deflated 19%)
  adding: miranda_dataset/images/16059.jpg (deflated 11%)
  adding: miranda_dataset/images/27225.jpg (deflated 6%)
  adding: miranda_dataset/images/8529.jpg (deflated 12%)
  adding: miranda_dataset/images/18496.jpg (deflated 33%)
  adding: miranda_dataset/images/32404.jpg (deflated 30%)
  adding: miranda_dataset/images/43945.jpg (deflated 29%)
  adding: miranda_dataset/images/59872.jpg (deflated 5%)
  adding: miranda_dataset/images/35420.jpg (deflated 8%)
  adding: miranda_dataset/images/33970.jpg (deflated 29%)
  adding: miranda_dataset/images/57004.jpg (deflated 45%)
  adding: miranda_dataset/images/38547.jpg (deflated 31%)
  adding: miranda_dataset/images/17836.jpg (deflated 40%)
  adding: miranda_dataset/images/21926.jpg (deflated 7%)
  adding: miranda_dataset/images/44668.jpg (deflated 17%)
  adding: miranda_dataset/images/57036.jpg (deflated 4%)
  adding: miranda_dataset/images/22867.jpg (deflated 20%)
  adding: miranda_dataset/images/6388.jpg (deflated 4%)
  adding: miranda_dataset/images/28324.jpg (deflated 29%)
  adding: miranda_dataset/images/52964.jpg (deflated 17%)
  adding: miranda_dataset/images/35042.jpg (deflated 16%)
  adding: miranda_dataset/images/19400.jpg (deflated 17%)
  adding: miranda_dataset/images/52925.jpg (deflated 20%)
  adding: miranda_dataset/images/17684.jpg (deflated 32%)
  adding: miranda_dataset/images/50893.jpg (deflated 6%)
  adding: miranda_dataset/images/15697.jpg (deflated 9%)
  adding: miranda_dataset/images/34199.jpg (deflated 11%)
  adding: miranda_dataset/images/28550.jpg (deflated 10%)
  adding: miranda_dataset/images/7583.jpg (deflated 10%)
  adding: miranda_dataset/images/12808.jpg (deflated 9%)
  adding: miranda_dataset/images/52878.jpg (deflated 17%)
  adding: miranda_dataset/images/26824.jpg (deflated 11%)
  adding: miranda_dataset/images/35785.jpg (deflated 34%)
  adding: miranda_dataset/images/59645.jpg (deflated 8%)
  adding: miranda_dataset/images/42656.jpg (deflated 5%)
  adding: miranda_dataset/images/26149.jpg (deflated 12%)
  adding: miranda_dataset/images/30941.jpg (deflated 7%)
  adding: miranda_dataset/images/13223.jpg (deflated 14%)
  adding: miranda_dataset/images/13246.jpg (deflated 16%)
  adding: miranda_dataset/images/32420.jpg (deflated 6%)
  adding: miranda_dataset/images/31123.jpg (deflated 28%)
  adding: miranda_dataset/images/4983.jpg (deflated 7%)
  adding: miranda_dataset/images/1884.jpg (deflated 36%)
  adding: miranda_dataset/images/11096.jpg (deflated 7%)
  adding: miranda_dataset/images/52522.jpg (deflated 21%)
  adding: miranda_dataset/images/22502.jpg (deflated 36%)
  adding: miranda_dataset/images/55643.jpg (deflated 49%)
  adding: miranda_dataset/images/11370.jpg (deflated 32%)
  adding: miranda_dataset/images/19333.jpg (deflated 18%)
  adding: miranda_dataset/images/26088.jpg (deflated 13%)
  adding: miranda_dataset/images/34586.jpg (deflated 23%)
  adding: miranda_dataset/images/44923.jpg (deflated 23%)
  adding: miranda_dataset/images/22137.jpg (deflated 27%)
  adding: miranda_dataset/images/49919.jpg (deflated 17%)
  adding: miranda_dataset/images/24908.jpg (deflated 30%)
  adding: miranda_dataset/images/16990.jpg (deflated 21%)
  adding: miranda_dataset/images/6547.jpg (deflated 24%)
  adding: miranda_dataset/images/7669.jpg (deflated 9%)
  adding: miranda_dataset/images/19475.jpg (deflated 5%)
  adding: miranda_dataset/images/1607.jpg (deflated 18%)
  adding: miranda_dataset/images/48104.jpg (deflated 18%)
  adding: miranda_dataset/images/49923.jpg (deflated 14%)
  adding: miranda_dataset/images/57950.jpg (deflated 32%)
  adding: miranda_dataset/images/14550.jpg (deflated 8%)
  adding: miranda_dataset/images/22330.jpg (deflated 9%)
  adding: miranda_dataset/images/24525.jpg (deflated 9%)
  adding: miranda_dataset/images/31699.jpg (deflated 8%)
  adding: miranda_dataset/images/43332.jpg (deflated 13%)
  adding: miranda_dataset/images/41608.jpg (deflated 5%)
  adding: miranda_dataset/images/32389.jpg (deflated 18%)
  adding: miranda_dataset/images/7883.jpg (deflated 13%)
  adding: miranda_dataset/images/19855.jpg (deflated 9%)
  adding: miranda_dataset/images/42275.jpg (deflated 5%)
  adding: miranda_dataset/images/31687.jpg (deflated 11%)
  adding: miranda_dataset/images/8492.jpg (deflated 9%)
  adding: miranda_dataset/images/47193.jpg (deflated 31%)
  adding: miranda_dataset/images/23186.jpg (deflated 10%)
  adding: miranda_dataset/images/13288.jpg (deflated 10%)
  adding: miranda_dataset/images/52920.jpg (deflated 7%)
  adding: miranda_dataset/images/40951.jpg (deflated 37%)
  adding: miranda_dataset/images/47279.jpg (deflated 29%)
  adding: miranda_dataset/images/44905.jpg (deflated 27%)
  adding: miranda_dataset/images/57513.jpg (deflated 31%)
  adding: miranda_dataset/images/4319.jpg (deflated 32%)
  adding: miranda_dataset/images/22488.jpg (deflated 43%)
  adding: miranda_dataset/images/48084.jpg (deflated 14%)
  adding: miranda_dataset/images/31673.jpg (deflated 17%)
  adding: miranda_dataset/images/42235.jpg (deflated 9%)
  adding: miranda_dataset/images/57061.jpg (deflated 19%)
  adding: miranda_dataset/images/20091.jpg (deflated 7%)
  adding: miranda_dataset/images/59650.jpg (deflated 17%)
  adding: miranda_dataset/images/28662.jpg (deflated 26%)
  adding: miranda_dataset/images/37560.jpg (deflated 22%)
  adding: miranda_dataset/images/40955.jpg (deflated 10%)
  adding: miranda_dataset/images/32852.jpg (deflated 19%)
  adding: miranda_dataset/images/44407.jpg (deflated 29%)
  adding: miranda_dataset/images/30551.jpg (deflated 8%)
  adding: miranda_dataset/images/41006.jpg (deflated 14%)
  adding: miranda_dataset/images/43624.jpg (deflated 4%)
  adding: miranda_dataset/images/12244.jpg (deflated 8%)
  adding: miranda_dataset/images/12186.jpg (deflated 6%)
  adding: miranda_dataset/images/11110.jpg (deflated 6%)
  adding: miranda_dataset/images/37765.jpg (deflated 2%)
  adding: miranda_dataset/images/50756.jpg (deflated 34%)
  adding: miranda_dataset/images/15859.jpg (deflated 17%)
  adding: miranda_dataset/images/55649.jpg (deflated 36%)
  adding: miranda_dataset/images/54727.jpg (deflated 6%)
  adding: miranda_dataset/images/28938.jpg (deflated 6%)
  adding: miranda_dataset/images/45604.jpg (deflated 31%)
  adding: miranda_dataset/images/56697.jpg (deflated 3%)
  adding: miranda_dataset/images/14103.jpg (deflated 12%)
  adding: miranda_dataset/images/54108.jpg (deflated 30%)
  adding: miranda_dataset/images/30937.jpg (deflated 7%)
  adding: miranda_dataset/images/24199.jpg (deflated 11%)
  adding: miranda_dataset/images/18758.jpg (deflated 14%)
  adding: miranda_dataset/images/4473.jpg (deflated 13%)
  adding: miranda_dataset/images/20213.jpg (deflated 11%)
  adding: miranda_dataset/images/44736.jpg (deflated 12%)
  adding: miranda_dataset/images/53035.jpg (deflated 7%)
  adding: miranda_dataset/images/57011.jpg (deflated 35%)
  adding: miranda_dataset/images/59966.jpg (deflated 4%)
  adding: miranda_dataset/images/15896.jpg (deflated 63%)
  adding: miranda_dataset/images/6147.jpg (deflated 32%)
  adding: miranda_dataset/images/1977.jpg (deflated 4%)
  adding: miranda_dataset/images/52976.jpg (deflated 19%)
  adding: miranda_dataset/images/9634.jpg (deflated 6%)
  adding: miranda_dataset/images/18763.jpg (deflated 17%)
  adding: miranda_dataset/images/39257.jpg (deflated 23%)
  adding: miranda_dataset/images/30879.jpg (deflated 12%)
  adding: miranda_dataset/images/13283.jpg (deflated 11%)
  adding: miranda_dataset/images/19246.jpg (deflated 9%)
  adding: miranda_dataset/images/43299.jpg (deflated 30%)
  adding: miranda_dataset/images/13915.jpg (deflated 32%)
  adding: miranda_dataset/images/47528.jpg (deflated 36%)
  adding: miranda_dataset/images/59212.jpg (deflated 8%)
  adding: miranda_dataset/images/41971.jpg (deflated 8%)
  adding: miranda_dataset/images/17692.jpg (deflated 39%)
  adding: miranda_dataset/images/14626.jpg (deflated 9%)
  adding: miranda_dataset/images/49958.jpg (deflated 7%)
  adding: miranda_dataset/images/9140.jpg (deflated 11%)
  adding: miranda_dataset/images/18735.jpg (deflated 11%)
  adding: miranda_dataset/images/59609.jpg (deflated 16%)
  adding: miranda_dataset/images/19818.jpg (deflated 17%)
  adding: miranda_dataset/images/37588.jpg (deflated 22%)
  adding: miranda_dataset/images/23305.jpg (deflated 12%)
  adding: miranda_dataset/images/29665.jpg (deflated 9%)
  adding: miranda_dataset/images/40196.jpg (deflated 2%)
  adding: miranda_dataset/images/31876.jpg (deflated 15%)
  adding: miranda_dataset/images/12874.jpg (deflated 43%)
  adding: miranda_dataset/images/13875.jpg (deflated 8%)
  adding: miranda_dataset/images/31474.jpg (deflated 16%)
  adding: miranda_dataset/images/6500.jpg (deflated 23%)
  adding: miranda_dataset/images/7325.jpg (deflated 14%)
  adding: miranda_dataset/images/42323.jpg (deflated 18%)
  adding: miranda_dataset/images/37190.jpg (deflated 23%)
  adding: miranda_dataset/images/14937.jpg (deflated 11%)
  adding: miranda_dataset/images/15209.jpg (deflated 9%)
  adding: miranda_dataset/images/33241.jpg (deflated 15%)
  adding: miranda_dataset/images/14627.jpg (deflated 11%)
  adding: miranda_dataset/images/33195.jpg (deflated 24%)
  adding: miranda_dataset/images/2637.jpg (deflated 29%)
  adding: miranda_dataset/images/57987.jpg (deflated 15%)
  adding: miranda_dataset/images/9063.jpg (deflated 6%)
  adding: miranda_dataset/images/22595.jpg (deflated 11%)
  adding: miranda_dataset/images/13470.jpg (deflated 10%)
  adding: miranda_dataset/images/52955.jpg (deflated 19%)
  adding: miranda_dataset/images/4026.jpg (deflated 35%)
  adding: miranda_dataset/images/12977.jpg (deflated 38%)
  adding: miranda_dataset/images/27204.jpg (deflated 10%)
  adding: miranda_dataset/images/3181.jpg (deflated 10%)
  adding: miranda_dataset/images/5481.jpg (deflated 11%)
  adding: miranda_dataset/images/59654.jpg (deflated 17%)
  adding: miranda_dataset/images/14547.jpg (deflated 11%)
  adding: miranda_dataset/images/30617.jpg (deflated 15%)
  adding: miranda_dataset/images/38539.jpg (deflated 26%)
  adding: miranda_dataset/images/41378.jpg (deflated 7%)
  adding: miranda_dataset/images/3481.jpg (deflated 46%)
  adding: miranda_dataset/images/46080.jpg (deflated 18%)
  adding: miranda_dataset/images/9602.jpg (deflated 5%)
  adding: miranda_dataset/images/11818.jpg (deflated 12%)
  adding: miranda_dataset/images/16052.jpg (deflated 9%)
  adding: miranda_dataset/images/10427.jpg (deflated 6%)
  adding: miranda_dataset/images/9229.jpg (deflated 7%)
  adding: miranda_dataset/images/13129.jpg (deflated 48%)
  adding: miranda_dataset/images/8448.jpg (deflated 10%)
  adding: miranda_dataset/images/13948.jpg (deflated 12%)
  adding: miranda_dataset/images/31457.jpg (deflated 10%)
  adding: miranda_dataset/images/15018.jpg (deflated 6%)
  adding: miranda_dataset/images/9778.jpg (deflated 10%)
  adding: miranda_dataset/images/50279.jpg (deflated 35%)
  adding: miranda_dataset/images/11364.jpg (deflated 18%)
  adding: miranda_dataset/images/35802.jpg (deflated 9%)
  adding: miranda_dataset/images/57105.jpg (deflated 21%)
  adding: miranda_dataset/images/45614.jpg (deflated 31%)
  adding: miranda_dataset/images/24113.jpg (deflated 32%)
  adding: miranda_dataset/images/11379.jpg (deflated 27%)
  adding: miranda_dataset/images/40387.jpg (deflated 11%)
  adding: miranda_dataset/images/26905.jpg (deflated 22%)
  adding: miranda_dataset/images/49364.jpg (deflated 35%)
  adding: miranda_dataset/images/8076.jpg (deflated 13%)
  adding: miranda_dataset/images/29266.jpg (deflated 18%)
  adding: miranda_dataset/images/5777.jpg (deflated 19%)
  adding: miranda_dataset/images/32470.jpg (deflated 19%)
  adding: miranda_dataset/images/52966.jpg (deflated 6%)
  adding: miranda_dataset/images/15174.jpg (deflated 19%)
  adding: miranda_dataset/images/41706.jpg (deflated 14%)
  adding: miranda_dataset/images/18722.jpg (deflated 10%)
  adding: miranda_dataset/images/57956.jpg (deflated 15%)
  adding: miranda_dataset/images/24510.jpg (deflated 7%)
  adding: miranda_dataset/images/17928.jpg (deflated 29%)
  adding: miranda_dataset/images/45596.jpg (deflated 33%)
  adding: miranda_dataset/images/57298.jpg (deflated 39%)
  adding: miranda_dataset/images/5288.jpg (deflated 4%)
  adding: miranda_dataset/images/13889.jpg (deflated 2%)
  adding: miranda_dataset/images/16506.jpg (deflated 20%)
  adding: miranda_dataset/images/8905.jpg (deflated 12%)
  adding: miranda_dataset/images/11761.jpg (deflated 11%)
  adding: miranda_dataset/images/42237.jpg (deflated 6%)
  adding: miranda_dataset/images/37135.jpg (deflated 19%)
  adding: miranda_dataset/images/46252.jpg (deflated 17%)
  adding: miranda_dataset/images/11305.jpg (deflated 21%)
  adding: miranda_dataset/images/4568.jpg (deflated 38%)
  adding: miranda_dataset/images/2222.jpg (deflated 26%)
  adding: miranda_dataset/images/46015.jpg (deflated 18%)
  adding: miranda_dataset/images/23210.jpg (deflated 11%)
  adding: miranda_dataset/images/18269.jpg (deflated 13%)
  adding: miranda_dataset/images/20946.jpg (deflated 51%)
  adding: miranda_dataset/images/58682.jpg (deflated 4%)
  adding: miranda_dataset/images/11447.jpg (deflated 36%)
  adding: miranda_dataset/images/20021.jpg (deflated 11%)
  adding: miranda_dataset/images/43664.jpg (deflated 20%)
  adding: miranda_dataset/images/17917.jpg (deflated 21%)
  adding: miranda_dataset/images/9145.jpg (deflated 7%)
  adding: miranda_dataset/images/54693.jpg (deflated 7%)
  adding: miranda_dataset/images/37628.jpg (deflated 29%)
  adding: miranda_dataset/images/6868.jpg (deflated 24%)
  adding: miranda_dataset/images/49962.jpg (deflated 26%)
  adding: miranda_dataset/images/13785.jpg (deflated 11%)
  adding: miranda_dataset/images/31335.jpg (deflated 11%)
  adding: miranda_dataset/images/45412.jpg (deflated 54%)
  adding: miranda_dataset/images/25503.jpg (deflated 14%)
  adding: miranda_dataset/images/7206.jpg (deflated 19%)
  adding: miranda_dataset/images/16375.jpg (deflated 11%)
  adding: miranda_dataset/images/10079.jpg (deflated 30%)
  adding: miranda_dataset/images/52943.jpg (deflated 13%)
  adding: miranda_dataset/images/15557.jpg (deflated 10%)
  adding: miranda_dataset/images/26260.jpg (deflated 11%)
  adding: miranda_dataset/images/7330.jpg (deflated 14%)
  adding: miranda_dataset/images/1976.jpg (deflated 3%)
  adding: miranda_dataset/images/51447.jpg (deflated 6%)
  adding: miranda_dataset/images/29779.jpg (deflated 10%)
  adding: miranda_dataset/images/47015.jpg (deflated 17%)
  adding: miranda_dataset/images/29255.jpg (deflated 22%)
  adding: miranda_dataset/images/23138.jpg (deflated 17%)
  adding: miranda_dataset/images/13558.jpg (deflated 31%)
  adding: miranda_dataset/images/14935.jpg (deflated 25%)
  adding: miranda_dataset/images/3657.jpg (deflated 37%)
  adding: miranda_dataset/images/8438.jpg (deflated 10%)
  adding: miranda_dataset/images/34114.jpg (deflated 14%)
  adding: miranda_dataset/images/19706.jpg (deflated 6%)
  adding: miranda_dataset/images/27561.jpg (deflated 4%)
  adding: miranda_dataset/images/14461.jpg (deflated 31%)
  adding: miranda_dataset/images/45574.jpg (deflated 33%)
  adding: miranda_dataset/images/12806.jpg (deflated 12%)
  adding: miranda_dataset/images/13106.jpg (deflated 9%)
  adding: miranda_dataset/images/37141.jpg (deflated 3%)
  adding: miranda_dataset/images/44726.jpg (deflated 38%)
  adding: miranda_dataset/images/23400.jpg (deflated 17%)
  adding: miranda_dataset/images/20874.jpg (deflated 29%)
  adding: miranda_dataset/images/44713.jpg (deflated 26%)
  adding: miranda_dataset/images/9170.jpg (deflated 11%)
  adding: miranda_dataset/images/49646.jpg (deflated 6%)
  adding: miranda_dataset/images/18175.jpg (deflated 35%)
  adding: miranda_dataset/images/29785.jpg (deflated 18%)
  adding: miranda_dataset/images/42556.jpg (deflated 5%)
  adding: miranda_dataset/images/23822.jpg (deflated 40%)
  adding: miranda_dataset/images/19721.jpg (deflated 17%)
  adding: miranda_dataset/images/13087.jpg (deflated 12%)
  adding: miranda_dataset/images/37111.jpg (deflated 6%)
  adding: miranda_dataset/images/12835.jpg (deflated 11%)
  adding: miranda_dataset/images/42093.jpg (deflated 34%)
  adding: miranda_dataset/images/13800.jpg (deflated 16%)
  adding: miranda_dataset/images/31434.jpg (deflated 11%)
  adding: miranda_dataset/images/5931.jpg (deflated 43%)
  adding: miranda_dataset/images/41377.jpg (deflated 3%)
  adding: miranda_dataset/images/43632.jpg (deflated 23%)
  adding: miranda_dataset/images/23624.jpg (deflated 32%)
  adding: miranda_dataset/images/18487.jpg (deflated 10%)
  adding: miranda_dataset/images/25962.jpg (deflated 21%)
  adding: miranda_dataset/images/53248.jpg (deflated 23%)
  adding: miranda_dataset/images/8388.jpg (deflated 13%)
  adding: miranda_dataset/images/15125.jpg (deflated 10%)
  adding: miranda_dataset/images/19523.jpg (deflated 10%)
  adding: miranda_dataset/images/59890.jpg (deflated 23%)
  adding: miranda_dataset/images/46082.jpg (deflated 32%)
  adding: miranda_dataset/images/13484.jpg (deflated 12%)
  adding: miranda_dataset/images/57202.jpg (deflated 5%)
  adding: miranda_dataset/images/16196.jpg (deflated 9%)
  adding: miranda_dataset/images/41785.jpg (deflated 5%)
  adding: miranda_dataset/images/13047.jpg (deflated 48%)
  adding: miranda_dataset/images/3452.jpg (deflated 12%)
  adding: miranda_dataset/images/50761.jpg (deflated 32%)
  adding: miranda_dataset/images/2711.jpg (deflated 3%)
  adding: miranda_dataset/images/59620.jpg (deflated 19%)
  adding: miranda_dataset/images/4897.jpg (deflated 2%)
  adding: miranda_dataset/images/18256.jpg (deflated 11%)

In [ ]:
from google.colab import files

files.download("miranda_dataset.zip")